*&---------------------------------------------------------------------*
*& Report  ZGSK_PP_MRP_EXCEPTIONS
*&---------------------------------------------------------------------*
*& MRP exception monitor for the manufacturing network. Reads the
*& classic MRP list (MDKP/MDTB) and raises exceptions for API and
*& drug-product materials at risk of stock-out.
*&
*& Object owner : GSC Planning IT
*& GxP class    : Non-GxP
*&---------------------------------------------------------------------*
REPORT zgsk_pp_mrp_exceptions.

TABLES: mdkp, mdtb, marc.

TYPES: BEGIN OF ty_exc,
         matnr  TYPE char18,
         werks  TYPE werks_d,
         dsdat  TYPE dsdat,
         dat00  TYPE dat00,
         delkz  TYPE delkz,
         mng01  TYPE mng01,
         ausch  TYPE ausch,
         plumi  TYPE plumi,
         dispo  TYPE dispo,
         beskz  TYPE beskz,
       END OF ty_exc.

DATA: gt_exc  TYPE STANDARD TABLE OF ty_exc WITH HEADER LINE,
      gt_mdkp TYPE STANDARD TABLE OF mdkp WITH HEADER LINE.

SELECT-OPTIONS: s_werks FOR mdkp-plwrk OBLIGATORY,
                s_dispo FOR marc-dispo,
                s_matnr FOR mdkp-matnr.

START-OF-SELECTION.

  PERFORM read_mrp_headers.
  PERFORM read_mrp_items.
  PERFORM output.

*&---------------------------------------------------------------------*
*&      Form  READ_MRP_HEADERS
*&---------------------------------------------------------------------*
FORM read_mrp_headers.

  SELECT * FROM mdkp
    INTO TABLE gt_mdkp
    WHERE plwrk IN s_werks
      AND matnr IN s_matnr
      AND dtart = 'MD'.

ENDFORM.

*&---------------------------------------------------------------------*
*&      Form  READ_MRP_ITEMS
*&---------------------------------------------------------------------*
* MRP list items read from MDTB by DTNUM. The list has to be
* regenerated by MD01 before this report runs.
*&---------------------------------------------------------------------*
FORM read_mrp_items.

  DATA: lt_mdtb TYPE STANDARD TABLE OF mdtb WITH HEADER LINE.

  LOOP AT gt_mdkp.

    SELECT * FROM mdtb
      INTO TABLE lt_mdtb
      WHERE dtnum = gt_mdkp-dtnum.

    LOOP AT lt_mdtb WHERE plumi = '-'.
      CLEAR gt_exc.
      gt_exc-matnr = gt_mdkp-matnr.
      gt_exc-werks = gt_mdkp-plwrk.
      gt_exc-dsdat = gt_mdkp-dsdat.
      gt_exc-dat00 = lt_mdtb-dat00.
      gt_exc-delkz = lt_mdtb-delkz.
      gt_exc-mng01 = lt_mdtb-mng01.
      gt_exc-plumi = lt_mdtb-plumi.

      SELECT SINGLE dispo beskz FROM marc
        INTO (gt_exc-dispo, gt_exc-beskz)
        WHERE matnr = gt_exc-matnr
          AND werks = gt_exc-werks.

      CHECK gt_exc-dispo IN s_dispo.
      APPEND gt_exc.
    ENDLOOP.

  ENDLOOP.

ENDFORM.

*&---------------------------------------------------------------------*
*&      Form  OUTPUT
*&---------------------------------------------------------------------*
FORM output.

  SORT gt_exc BY werks dispo matnr dat00.

  LOOP AT gt_exc.
    WRITE: / gt_exc-werks, gt_exc-dispo, gt_exc-matnr,
             gt_exc-dat00, gt_exc-delkz, gt_exc-mng01.
  ENDLOOP.

ENDFORM.
